{{- if .Values.ingress.enabled -}}
{{- $fullName := include "angular-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: nginx-example
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: {{ $svcPort }}
  # rules:
  # - http:
  #     paths:
  #     - path: /angular
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: angular
  #           port:
  #             number: 80
{{- end }}
