{{- if .Values.ingress.enabled -}}
{{- $fullName := include "angular-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    {{- with .Values.ingress.isCloud }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /angular(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
